---
Name: dashboard
---
Member:
  extensions:
    [DashboardMember]

SiteConfig:
  extensions:
    [DashboardSiteConfig]
GridFieldDetailForm_ItemRequest:
  extensions:
    [DashboardItemEditForm]
DashboardGoogleAnalyticsPanel:
  email: ''
  profile: ''
  key_file_path: google_oauth.p12